; PlatformIO Project Configuration
; FISCuntrolCAN - ESP32 DevKit V1

[env:esp32doit-devkit-v1]
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board     = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed  = 921600
board_build.partitions = min_spiffs.csv
board_build.filesystem = littlefs
build_flags =
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    me-no-dev/AsyncTCP
    me-no-dev/ESPAsyncWebServer
    bblanchon/ArduinoJson
    mathertel/OneButton
    adafruit/RTClib
    git+https://github.com/domnulvlad/TLBFISLib.git
    git+https://github.com/domnulvlad/KLineKWP1281Lib_ESP32.git
    git+https://github.com/domnulvlad/TLBLib.git
